<?php 
$productIT = array (
  'product_name' => 'Product Name',
  'published' => '1',
  'product_special' => '0',
  'product_discontinued' => '0',
  'slug' => 'product-name',
  'product_sku' => 'Product SKu',
  'product_gtin' => '09092082070726',
  'product_mpn' => 'MPN09876',
  'virtuemart_manufacturer_id' => 
  array (
    0 => '1',
  ),
  'layout' => '',
  'product_url' => '',
  'categories' => 
  array (
    0 => '5',
    1 => '4',
  ),
  'virtuemart_shoppergroup_id' => 
  array (
    0 => '2',
  ),
  'virtuemart_shoppergroup_set' => '1',
  'mprices' => 
  array (
    'product_price' =>     array (      0 => '35',    ),
    'virtuemart_product_price_id' =>     array (      0 => '25',    ),
    'product_currency' =>     array (      0 => '47',    ),
    'virtuemart_shoppergroup_id' =>     array (      0 => '',    ),
    'basePrice' =>     array (      0 => '35',    ),
    'product_tax_id' =>     array (      0 => '1',    ),
    'salesPrice' =>     array (      0 => '43.05',    ),
    'product_discount_id' =>     array (      0 => '-1',    ),
    'product_price_publish_up' =>     array (      0 => '0',    ),
    'product_price_publish_down' =>     array (      0 => '0',    ),
    'product_override_price' =>     array (      0 => '0',    ),
    'override' =>     array (      0 => '0',    ),
    'price_quantity_start' =>     array (      0 => '0',    ),
    'price_quantity_end' =>     array (      0 => '0',
    ),
  ),
  
  "product_full_image"=>"http://localhost.dev/immaginiEbay/maglie/argentinav31429/det-adV31429-1.jpg",
//  "product_full_image"=>"http://localhost.dev/immaginiEbay/maglie/argentinav31429/det-pu739854-1.jpg",
    'imagesArray' => array(
        array(             'big'=> "http://localhost.dev/immaginiEbay/maglie/argentinav31429/det-adV31429-1.jpg",             'thumb'=>"http://localhost.dev/immaginiEbay/maglie/argentinav31429/tmb_det-adV31429-1.jpg"),
        array(             'big'=> "http://localhost.dev/immaginiEbay/maglie/argentinav31429/det-adV31429-2.jpg",             'thumb'=>"http://localhost.dev/immaginiEbay/maglie/argentinav31429/tmb_det-adV31429-2.jpg"),
        array(             'big'=> "http://localhost.dev/immaginiEbay/maglie/argentinav31429/det-adV31429-3.jpg",             'thumb'=>"http://localhost.dev/immaginiEbay/maglie/argentinav31429/tmb_det-adV31429-3.jpg"),
//        array(             'big'=> "http://localhost.dev/immaginiEbay/maglie/argentinav31429/det-adV31429-4.jpg",             'thumb'=>"http://localhost.dev/immaginiEbay/maglie/argentinav31429/tmb_det-adV31429-4.jpg"),
//        array(             'big'=> "http://localhost.dev/immaginiEbay/maglie/argentinav31429/det-adV31429-5.jpg",             'thumb'=>"http://localhost.dev/immaginiEbay/maglie/argentinav31429/tmb_det-adV31429-5.jpg"),
//        array(             'big'=> "http://localhost.dev/immaginiEbay/maglie/argentinav31429/det-adV31429-6.jpg",             'thumb'=>"http://localhost.dev/immaginiEbay/maglie/argentinav31429/tmb_det-adV31429-6.jpg"),
        
    ),
  'product_parent_id' => '0',
  'intnotes' => 'Internal note',
  'product_s_desc' => 'short Description',
  'product_desc' => '<p>Long Description</p>',
  'customtitle' => 'Page Title',
  'metakey' => 'Meta Keywords',
  'metadesc' => 'Meta description',
  'metarobot' => '',
  'metaauthor' => '',
  'product_in_stock' => '10',
  'product_ordered' => '0',
  'low_stock_notification' => '5',
  'step_order_level' => '',
  'min_order_level' => '',
  'max_order_level' => '',
  'product_available_date' => '2017-04-04 00:00:00',
  'product_availability' => '',
  'image' => '',
  'customer_email_type' => 'customer',
  'notification_template' => '1',
  'notify_number' => '',
  'product_length' => '',
  'product_lwh_uom' => 'M',
  'product_width' => '',
  'product_height' => '',
  'product_weight' => '0.5000',
  'product_weight_uom' => 'KG',
  'product_packaging' => '',
  'product_unit' => 'KG',
  'product_box' => '',
  'searchMedia' => '',
  'media' => 
  array (
    'media_published' => '1',
    'file_title' => '',
    'file_description' => '',
    'file_meta' => '',
    'file_class' => '',
    'file_url' => 'images/stories/virtuemart/product/',
    'file_url_thumb' => '',
    'media_roles' => 'file_is_displayable',
    'media_action' => '0',
    'active_media_id' => '0',
  ),
  'file_is_product_image' => '1',
  'option' => 'com_virtuemart',
  'search' => '',
  'customlist' => '7',
   
  'field' => 
  array (
    0 => 
    array (
      'field_type' => 'S',
      'custom_element' => '0',
      'custom_jplugin_id' => '0',
      'virtuemart_custom_id' => '8',
      'virtuemart_product_id' => '65',
      'virtuemart_customfield_id' => '67',
      'ordering' => '0',
      'customfield_value' => 'Ciao',
    ),
    2 => 
    array (
      'field_type' => 'S',
      'custom_element' => '0',
      'custom_jplugin_id' => '0',
      'virtuemart_custom_id' => '15',
      'virtuemart_product_id' => '65',
      'virtuemart_customfield_id' => '0',
      'ordering' => '1',
      'customfield_value' => 'S',
    ),
    3 => 
    array (
      'field_type' => 'S',
      'custom_element' => '0',
      'custom_jplugin_id' => '0',
      'virtuemart_custom_id' => '15',
      'virtuemart_product_id' => '65',
      'virtuemart_customfield_id' => '0',
      'ordering' => '2',
      'customfield_value' => 'M',
    ),
    4 => 
    array (
      'field_type' => 'S',
      'custom_element' => '0',
      'custom_jplugin_id' => '0',
      'virtuemart_custom_id' => '7',
      'virtuemart_product_id' => '65',
      'virtuemart_customfield_id' => '0',
      'ordering' => '3',
      'customfield_value' => 'Navy',
    ),
  ),
  'task' => 'apply',
  'boxchecked' => '0',
  'controller' => 'product',
  'view' => 'product',
//  '28eda4d5c173150584be4bbe1ac7c3b6' => '1',
//  'virtuemart_product_id' => '49',
);